export const mobileFilters = [
  {
    id: 'category',
    name: 'Category',
    type: 'accordion',
  },
  {
    id: 'year',
    name: 'Year of production',
    type: 'accordion',
  },
  {
    id: 'country',
    name: 'Country of sale',
    type: 'accordion',
  },
  {
    name: 'Closes soon',
    type: 'checkbox',
  },
  {
    name: 'Recently added',
    type: 'checkbox',
  },
];

export const countries = [
  'Any',
  'Germany',
  'Switzerland',
  'Austria',
  'Belgium',
  'France',
  'Ireland',
  'Italy',
  'Luxembourg',
  'Netherlands',
  'Portugal',
  'Spain',
  'United Kingdom',
];
export const categories = [
  'Furniture',
  'Seating',
  'Lighting',
  'Porcelain',
  'Faience',
  'Other ceramics',
  'Silverware',
  'Glassware',
  'Sculptures',
  'Paintings',
  'Graphic arts',
  'Decorative arts',
  'Mirrors',
  'Architectural elements',
  'Clocks & Watches',
  'Jewelry',
  'Textile art',
  'Clothing',
  'Collectibles',
  'Religious & Ritual art',
  'Militaria',
  'Other',
];

export const categoriesFilter = [
  {
    category: 'Art',
    subCategories: [
      'Paintings',
      'Sculptureand bronzes',
      'Drawings watercolors and pastels',
      'Photography',
      'Posters',
      'Prints and limited editions',
    ],
  },
  {
    category: 'Furniture',
    subCategories: [
      'Table',
      'Secretary desk and vanity',
      'Bed and headboard',
      'Sofa and bench',
      'Chair and stool',
      'Armchair',
      'Pouf and footstool',
      'Drawer',
      'other',
    ],
  },
  {
    category: 'Decoration',
    subCategories: [
      'Rugs and tapestries',
      'Textiles and lace',
      'Ceramics and porcelain',
      'Tableware and goldsmithing',
      'Clocks',
      'Decorative objects',
      'Lighting',
      'Other',
    ],
  },
  {
    category: 'Fashion and jewellery',
    subCategories: [
      'Bags',
      'Clothing',
      'Fashion accessories',
      'Shoes',
      'Jewellery',
      'Diamonds and gemstones',
      'Watches',
      'Pens and lighters',
    ],
  },
  {
    category: 'Collectibles',
    subCategories: [
      'Books manuscripts and comics',
      'Historical memorabilia militaria and weapons',
      'Toys and models',
      'Music cinema and sports memorabilia',
      'Coins',
      'Stamps',
      'Maps',
      'Wine and spirits',
      'Trading cards',
    ],
  },
  {
    category: 'Vehicles and equipment goods',
    subCategories: [
      'Sports and collection cars',
      'Sports and collection motorcycles and scooters',
      'Bicycles and sports equipment',
      'Personal vehicles',
      'Professional vehicles',
      'It and telephony',
      'Household appliances',
      'Professional equipment',
    ],
  },
  {
    category: 'World art',
    subCategories: [
      'Africa',
      'China',
      'India',
      'Islamic',
      'Japan',
      'South east asia',
      'Oeania',
      'Americas',
    ],
  },
];
